export const path = {
  home: "/",
  login: "/login",
  signUp: "/sign-up",
  danhMucKhoaHoc: "/Danh-muc-khoa-hoc",
  khoaHocDetail: "/Chi-tiet-khoa-hoc",
  timKiemKhoaHoc: "/Tim-kiem-khoa-hoc",
  userInfo: "/user-info",
  adminInfor: "admin-info",
  userLessonResgister: "/user-lesson",
  admin: "/admin",
  listUser: "/admin/list-user",
  createUser: "/admin/create-user",
  quanLyKhoaHoc: "course-management",
};
